<?php
$base = __DIR__ . '/app';

/******************************************
 * 1. Intent Generation
 ******************************************/

$intents = [
    'Transactions/CreateTransactionIntent' => "<?php\nnamespace App\Intents\Transactions;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\TransactionService;\nuse Carbon\Carbon;\nclass CreateTransactionIntent implements IntentInterface {\n    public function __construct(protected TransactionService \$transactionService) {}\n    public function handle(array \$params): array {\n        if (empty(\$params['category']) && !empty(\$params['category_name'])) { \$params['category'] = \$params['category_name']; }\n        if (empty(\$params['category'])) { \$params['category'] = 'Lainnya'; }\n        if (empty(\$params['transaction_date'])) {\n            \$dateVal = strtolower(trim(\$params['date'] ?? ''));\n            if (in_array(\$dateVal, ['today', 'hari ini', ''])) \$params['transaction_date'] = Carbon::now()->format('Y-m-d');\n            elseif (in_array(\$dateVal, ['yesterday', 'kemarin'])) \$params['transaction_date'] = Carbon::now()->subDay()->format('Y-m-d');\n            else {\n                try { \$params['transaction_date'] = Carbon::parse(\$dateVal)->format('Y-m-d'); } catch (\Throwable \$e) { \$params['transaction_date'] = Carbon::now()->format('Y-m-d'); }\n            }\n        }\n        \$transaction = \$this->transactionService->createTransaction(\$params);\n        return ['intent' => 'create_transaction', 'status' => 'success', 'message' => 'Transaksi berhasil dicatat oleh Bot', 'transaction' => \$transaction];\n    }\n}",
    
    'Transactions/UpdateTransactionIntent' => "<?php\nnamespace App\Intents\Transactions;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\TransactionService;\nuse InvalidArgumentException;\nclass UpdateTransactionIntent implements IntentInterface {\n    public function __construct(protected TransactionService \$transactionService) {}\n    public function handle(array \$params): array {\n        \$id = \$params['id'] ?? null;\n        if (empty(\$id)) {\n            \$latest = \$this->transactionService->getLatestTransaction();\n            if (!\$latest) throw new InvalidArgumentException(\"Belum ada transaksi yang dapat diperbarui.\");\n            \$id = \$latest->id;\n        }\n        if (empty(\$params['category']) && !empty(\$params['category_name'])) { \$params['category'] = \$params['category_name']; }\n        \$transaction = \$this->transactionService->updateTransaction(\$id, \$params);\n        return ['intent' => 'update_transaction', 'status' => 'success', 'message' => 'Transaksi berhasil diperbarui', 'transaction' => \$transaction];\n    }\n}",

    'Transactions/DeleteTransactionIntent' => "<?php\nnamespace App\Intents\Transactions;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\TransactionService;\nuse InvalidArgumentException;\nclass DeleteTransactionIntent implements IntentInterface {\n    public function __construct(protected TransactionService \$transactionService) {}\n    public function handle(array \$params): array {\n        \$id = \$params['id'] ?? null;\n        if (empty(\$id)) {\n            \$latest = \$this->transactionService->getLatestTransaction();\n            if (!\$latest) throw new InvalidArgumentException(\"Belum ada transaksi yang dapat dihapus.\");\n            \$id = \$latest->id;\n        }\n        \$this->transactionService->deleteTransaction(\$id);\n        return ['intent' => 'delete_transaction', 'status' => 'success', 'message' => \"Transaksi ID {\$id} berhasil dihapus\"];\n    }\n}",

    'Statistics/StatisticsIntent' => "<?php\nnamespace App\Intents\Statistics;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\StatisticService;\nuse App\Services\DashboardService;\nclass StatisticsIntent implements IntentInterface {\n    public function __construct(protected StatisticService \$statisticService, protected DashboardService \$dashboardService) {}\n    public function handle(array \$params): array {\n        return ['intent' => 'statistics', 'summary' => \$this->dashboardService->getSummaryMetrics(), 'expense_by_category' => \$this->statisticService->getExpenseByCategoryChartData()];\n    }\n}",
    
    'Statistics/ReportIntent' => "<?php\nnamespace App\Intents\Statistics;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\ReportService;\nuse Carbon\Carbon;\nclass ReportIntent implements IntentInterface {\n    public function __construct(protected ReportService \$reportService) {}\n    public function handle(array \$params): array {\n        \$intent = \$params['_active_intent'] ?? 'daily_report';\n        \$now = Carbon::now();\n        if (\$intent === 'daily_report') {\n            \$date = \$params['date'] ?? \$now->format('Y-m-d');\n            return ['intent' => 'daily_report', 'report' => \$this->reportService->getDailyReport(\$date)];\n        } elseif (\$intent === 'weekly_report') {\n            \$startDate = \$params['start_date'] ?? \$now->copy()->startOfWeek()->format('Y-m-d');\n            \$endDate = \$params['end_date'] ?? \$now->copy()->endOfWeek()->format('Y-m-d');\n            return ['intent' => 'weekly_report', 'report' => \$this->reportService->getWeeklyReport(\$startDate, \$endDate)];\n        } elseif (\$intent === 'monthly_report') {\n            \$year = (int) (\$params['year'] ?? \$now->year);\n            \$month = (int) (\$params['month'] ?? \$now->month);\n            return ['intent' => 'monthly_report', 'report' => \$this->reportService->getMonthlyReport(\$year, \$month)];\n        }\n        return [];\n    }\n}",

    'Budgets/BudgetSummaryIntent' => "<?php\nnamespace App\Intents\Budgets;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\DashboardService;\nclass BudgetSummaryIntent implements IntentInterface {\n    public function __construct(protected DashboardService \$dashboardService) {}\n    public function handle(array \$params): array {\n        return ['intent' => 'budget', 'metrics' => \$this->dashboardService->getSummaryMetrics()];\n    }\n}",
    
    'Budgets/CreateBudgetIntent' => "<?php\nnamespace App\Intents\Budgets;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\BudgetService;\nclass CreateBudgetIntent implements IntentInterface {\n    public function __construct(protected BudgetService \$service) {}\n    public function handle(array \$params): array {\n        \$res = \$this->service->create(\$params);\n        return ['intent' => 'create_budget', 'status' => 'success', 'message' => 'Budget berhasil dibuat', 'budget' => \$res];\n    }\n}",

    'Reminders/CreateReminderIntent' => "<?php\nnamespace App\Intents\Reminders;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\ReminderService;\nclass CreateReminderIntent implements IntentInterface {\n    public function __construct(protected ReminderService \$service) {}\n    public function handle(array \$params): array {\n        \$res = \$this->service->create(\$params);\n        return ['intent' => 'create_reminder', 'status' => 'success', 'message' => 'Pengingat berhasil dibuat', 'reminder' => \$res];\n    }\n}",

    'Bills/CreateBillIntent' => "<?php\nnamespace App\Intents\Bills;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\RecurringBillService;\nclass CreateBillIntent implements IntentInterface {\n    public function __construct(protected RecurringBillService \$service) {}\n    public function handle(array \$params): array {\n        if (isset(\$params['auto_create_transaction']) && \$params['auto_create_transaction'] === 'true') \$params['auto_create_transaction'] = true;\n        if (isset(\$params['auto_create_transaction']) && \$params['auto_create_transaction'] === 'false') \$params['auto_create_transaction'] = false;\n        \$res = \$this->service->create(\$params);\n        return ['intent' => 'create_bill', 'status' => 'success', 'message' => 'Tagihan rutin berhasil dibuat', 'bill' => \$res];\n    }\n}",

    'SavingGoals/CreateSavingGoalIntent' => "<?php\nnamespace App\Intents\SavingGoals;\nuse App\Intents\Contracts\IntentInterface;\nuse App\Services\SavingGoalService;\nclass CreateSavingGoalIntent implements IntentInterface {\n    public function __construct(protected SavingGoalService \$service) {}\n    public function handle(array \$params): array {\n        \$res = \$this->service->create(\$params);\n        return ['intent' => 'create_saving_goal', 'status' => 'success', 'message' => 'Target tabungan berhasil dibuat', 'saving_goal' => \$res];\n    }\n}",

    'System/HelpIntent' => "<?php\nnamespace App\Intents\System;\nuse App\Intents\Contracts\IntentInterface;\nclass HelpIntent implements IntentInterface {\n    public function handle(array \$params): array {\n        return [\n            'intent' => 'help',\n            'available_intents' => [\n                'create_transaction' => 'Mencatat transaksi baru',\n                'update_transaction' => 'Memperbarui transaksi',\n                'delete_transaction' => 'Menghapus transaksi',\n                'statistics' => 'Mengambil statistik ringkas keuangan',\n                'daily_report' => 'Mengambil laporan harian',\n                'weekly_report' => 'Mengambil laporan mingguan',\n                'monthly_report' => 'Mengambil laporan bulanan',\n                'budget' => 'Melihat ringkasan saldo & kas',\n                'create_reminder' => 'Membuat pengingat',\n                'create_bill' => 'Membuat tagihan rutin',\n                'create_budget' => 'Membuat batas anggaran bulanan',\n                'create_saving_goal' => 'Membuat target tabungan',\n                'help' => 'Menampilkan daftar intent bot',\n            ],\n        ];\n    }\n}"
];

foreach ($intents as $path => $content) {
    $fullPath = "$base/Intents/$path.php";
    $dir = dirname($fullPath);
    if (!is_dir($dir)) mkdir($dir, 0777, true);
    file_put_contents($fullPath, $content);
}

/******************************************
 * 2. Overwriting BotService.php
 ******************************************/
$botServiceContent = "<?php\n\nnamespace App\Services;\n\nclass BotService\n{\n    public function __construct(\n        protected IntentDispatcherService \$dispatcher\n    ) {}\n\n    /**\n     * Execute bot intent payload from n8n / Telegram Bot.\n     */\n    public function executeIntent(string \$intent, array \$parameters = []): array\n    {\n        // Pass intent directly to IntentDispatcherService\n        return \$this->dispatcher->dispatch(\$intent, \$parameters);\n    }\n}\n";
file_put_contents("$base/Services/BotService.php", $botServiceContent);

/******************************************
 * 3. Wiring up IntentDispatcherService
 ******************************************/
$dispatcherContent = file_get_contents("$base/Services/IntentDispatcherService.php");
// Change namespace for intent interface
$dispatcherContent = str_replace("use App\Intents\IntentInterface;", "use App\Intents\Contracts\IntentInterface;", $dispatcherContent);

// Also missing budget mapping
$dispatcherContent = str_replace("        'budget_summary' => \App\Intents\Budgets\BudgetSummaryIntent::class,", "        'budget' => \App\Intents\Budgets\BudgetSummaryIntent::class,\n        'balance' => \App\Intents\Budgets\BudgetSummaryIntent::class,", $dispatcherContent);
file_put_contents("$base/Services/IntentDispatcherService.php", $dispatcherContent);

echo "Intent layer completely refactored.\n";
